CREATE TABLE matches (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	leaderboard_id INTEGER NOT NULL REFERENCES leaderboards(id) ON DELETE CASCADE,
	player1_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
	player2_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
	score VARCHAR(10) NOT NULL,
	winner_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
	played_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CHECK (winner_id IN (player1_id, player2_id))
);
