CREATE TABLE players (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	leaderboard_id INTEGER NOT NULL REFERENCES leaderboards(id) ON DELETE CASCADE,
	username VARCHAR(255) NOT NULL,
	matches_won INTEGER NOT NULL DEFAULT 0,
	matches_drawn INTEGER NOT NULL DEFAULT 0,
	matches_lost INTEGER NOT NULL DEFAULT 0,
	total_games_won INTEGER NOT NULL DEFAULT 0,
	total_games_lost INTEGER NOT NULL DEFAULT 0,
	current_streak INTEGER NOT NULL DEFAULT 0,
	elo INTEGER NOT NULL DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (leaderboard_id, username)
);
