CREATE TABLE webhooks (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	leaderboard_id INTEGER REFERENCES leaderboards(id) ON DELETE CASCADE,
	url TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(leaderboard_id, url)
);
